### ISSUE TITLE
打包前端的时候，会出现一点小问题

### ISSUE THREAD

**Issue by nanshaws** [Alanyaeer/oj-project-client#1]
图：
![image](https://github.com/Alanyaeer/oj-project-client/assets/98329722/5ca75bf6-e97e-49cd-a954-6f5b01af7894)
解决方案：将这个空白文件进行删除
![image](https://github.com/Alanyaeer/oj-project-client/assets/98329722/79a4bd3d-4307-42f9-81f2-5dd5f7092117)
或者写点以下代码：
<template>
  <div>
    
  </div>
</template>

<script>
export default {
  // 组件的逻辑部分
}
</script>

**Comment by nanshaws** [comment]
<template>
  <div>
    
  </div>
</template>

<script>
export default {
  // 组件的逻辑部分
}
</script>

**Comment by Alanyaeer** [comment]
欸奇怪了我之前应该打包的时候把这个文件删掉了呀？？

**Comment by nanshaws** [comment]
![image](https://github.com/Alanyaeer/oj-project-client/assets/98329722/d91925ea-0acd-402c-b73e-dfd75a0408e1)

**Comment by nanshaws** [comment]
哦哦哦，我好像用的是老版本的

**Comment by Alanyaeer** [comment]
可能得 `pnpm run build`
